
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "ford",
    "model": "mustang",
    "year": 1982,
    "mileage": 50000,
    "lng": 45,
    "lat": 45,
    "price": 20000
}

### Approving the existing report
PATCH  http://localhost:3000/reports/12
content-type: application/json

{
    "approved" : true
}

### get an estimate for an existing vehicle
Get http://localhost:3000/reports?make=ford&model=mustang&lng=45&lat=45&mileage=20000&year=1981