
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "toyota",
    "model": "corolla",
    "year": 1980,
    "mileage": 1000,
    "lng": 0,
    "lat": 0,
    "price": 50000
}

### Approving the existing report
PATCH  http://localhost:3000/reports/1
content-type: application/json

{
    "approved" : true
}