### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"new@gmail.com",
    "password":"password" 
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/3

### Find all users with a given email
GET http://localhost:3000/auth?email=hhuh@gmail.com

### Delete a user given id
DELETE  http://localhost:3000/auth/3


### update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email":"xyz@abc.com"
}